/*
PROJETO 01: Análise de Estoque e Vendas - Varejo de Aventura
AUTOR: Vinicios
DATA: Fevereiro/2026
FERRAMENTA: Oracle SQL
DESCRIÇÃO: Identificação de produtos com baixo giro (encalhados) e cálculo de ticket médio.
*/

-- ==========================================
-- 1. CRIAÇÃO DAS TABELAS (DDL)
-- ==========================================

CREATE TABLE tb_produtos (
    id_produto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_produto VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50) NOT NULL,
    quantidade_estoque NUMBER NOT NULL,
    preco_unitario NUMBER(10,2) NOT NULL
);

CREATE TABLE tb_vendas (
    id_venda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto NUMBER REFERENCES tb_produtos(id_produto),
    data_venda DATE NOT NULL,
    quantidade_vendida NUMBER NOT NULL,
    valor_total NUMBER(10,2) NOT NULL
);

-- ==========================================
-- 2. INSERÇÃO DE DADOS (DML)
-- Nota: Dados gerados com auxílio de IA para simular cenários de borda.
-- ==========================================

INSERT INTO tb_produtos (nome_produto, categoria, quantidade_estoque, preco_unitario) VALUES ('Barraca Ultra Leve 2P', 'Camping', 15, 850.00);
INSERT INTO tb_produtos (nome_produto, categoria, quantidade_estoque, preco_unitario) VALUES ('Corda Dinâmica 50m', 'Escalada', 8, 1200.00);
INSERT INTO tb_produtos (nome_produto, categoria, quantidade_estoque, preco_unitario) VALUES ('Bota Impermeável', 'Trilha', 20, 650.00);
INSERT INTO tb_produtos (nome_produto, categoria, quantidade_estoque, preco_unitario) VALUES ('Mosquetão de Alumínio', 'Escalada', 150, 45.00);
INSERT INTO tb_produtos (nome_produto, categoria, quantidade_estoque, preco_unitario) VALUES ('Saco de Dormir -5C', 'Camping', 60, 420.00);

-- Vendas (Cenário: Alguns produtos vendem bem, outros não)
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (3, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 1, 650.00);
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (1, TO_DATE('2026-01-15', 'YYYY-MM-DD'), 2, 1700.00);
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (3, TO_DATE('2026-02-05', 'YYYY-MM-DD'), 1, 650.00);
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (2, TO_DATE('2026-02-10', 'YYYY-MM-DD'), 1, 1200.00);
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (4, TO_DATE('2026-02-12', 'YYYY-MM-DD'), 2, 90.00);
INSERT INTO tb_vendas (id_produto, data_venda, quantidade_vendida, valor_total) VALUES (4, TO_DATE('2026-02-16', 'YYYY-MM-DD'), 1, 45.00);

COMMIT;

-- ==========================================
-- 3. SOLUÇÃO DAS PERGUNTAS DE NEGÓCIO
-- ==========================================

-- Questão 1: Quais categorias geram o maior ticket médio?
SELECT 
    p.categoria,
    ROUND(AVG(v.valor_total), 2) AS ticket_medio
FROM TB_PRODUTOS p
JOIN TB_VENDAS v ON p.ID_PRODUTO = v.ID_PRODUTO 
GROUP BY p.categoria
ORDER BY ticket_medio DESC;

-- Questão 2: Quais produtos estão "encalhados" (Estoque alto, Venda baixa)?
-- Lógica: Usamos LEFT JOIN para incluir produtos que nunca venderam (NULL) e COALESCE para tratar como 0.
SELECT 
    p.nome_produto,
    p.quantidade_estoque,
    COALESCE(SUM(v.quantidade_vendida), 0) AS total_unidades_vendidas
FROM tb_produtos p
LEFT JOIN tb_vendas v ON p.id_produto = v.id_produto
WHERE p.quantidade_estoque > 50 
GROUP BY p.nome_produto, p.quantidade_estoque
HAVING COALESCE(SUM(v.quantidade_vendida), 0) < 3
ORDER BY total_unidades_vendidas ASC;